language: go
go:
  - "1.11"
os:
  - linux
  - osx
  - windows
env:
  - GO111MODULE=on
install: []
script:
  - go generate
  - go build -ldflags="-X main.version=$(git describe --always --long --dirty)"
  - go test
