FROM ruby:2.2.7-alpine

VOLUME /massikone
EXPOSE 5000

ENV BUNDLE_WITHOUT=mysql:pg
ENV RACK_ENV=development
ENV DATABASE_URL=sqlite:///massikone/data/massikone.db

RUN apk add --update imagemagick build-base sqlite sqlite-dev
RUN echo "gem: --no-rdoc --no-ri" > /etc/gemrc
RUN addgroup massikone && adduser -D -G massikone massikone -H /home/massikone

COPY . /massikone
WORKDIR /massikone
RUN bundle install
RUN chown -R massikone:massikone .
USER massikone
CMD puma -p 5000
