version: "2"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/massikone/data
    env_file:
      - .env
    environment:
      DATABASE_URL: "sqlite:///massikone/data/massikone.db"
